/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg autoTest;
  
  reg failCase;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_2 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  wire [16-1:0] M_alu_out;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  wire [1-1:0] M_alu_overflow;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_3 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n),
    .overflow(M_alu_overflow)
  );
  
  wire [16-1:0] M_reg_geta;
  wire [16-1:0] M_reg_getb;
  reg [1-1:0] M_reg_clk;
  reg [1-1:0] M_reg_buttonA;
  reg [1-1:0] M_reg_buttonB;
  reg [16-1:0] M_reg_switch;
  register_4 L_reg (
    .clk(M_reg_clk),
    .buttonA(M_reg_buttonA),
    .buttonB(M_reg_buttonB),
    .switch(M_reg_switch),
    .geta(M_reg_geta),
    .getb(M_reg_getb)
  );
  
  
  localparam IDLE_state = 2'd0;
  localparam INPUTA_state = 2'd1;
  localparam INPUTB_state = 2'd2;
  localparam OUTPUT_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = IDLE_state;
  
  wire [16-1:0] M_autotest_out;
  wire [24-1:0] M_autotest_leds;
  autotest_5 autotest (
    .clk(clk),
    .rst(rst),
    .mode_switch(autoTest),
    .out(M_autotest_out),
    .leds(M_autotest_leds)
  );
  
  wire [16-1:0] M_fc_out;
  fail_case_6 fc (
    .clk(clk),
    .rst(rst),
    .mode_switch(failCase),
    .out(M_fc_out)
  );
  
  always @* begin
    M_state_d = M_state_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = {3'h0, io_button};
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_seg_values = 16'h0000;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    io_led = io_dip;
    M_reg_clk = clk;
    M_reg_buttonA = io_button[3+0-:1];
    M_reg_buttonB = io_button[4+0-:1];
    M_reg_switch[0+7-:8] = io_dip[0+7-:8];
    M_reg_switch[8+7-:8] = io_dip[8+7-:8];
    autoTest = ~io_dip[16+7+0-:1];
    failCase = io_dip[16+6+0-:1];
    
    case (M_state_q)
      IDLE_state: begin
        if (io_button[1+0-:1]) begin
          M_state_d = INPUTA_state;
        end
      end
      INPUTA_state: begin
        M_seg_values = 16'h000b;
        io_led[0+7-:8] = M_reg_geta[0+7-:8];
        io_led[8+7-:8] = M_reg_geta[8+7-:8];
        if (io_button[1+0-:1]) begin
          M_state_d = OUTPUT_state;
        end else begin
          if (io_button[2+0-:1]) begin
            M_state_d = INPUTB_state;
          end
        end
      end
      INPUTB_state: begin
        io_led[0+7-:8] = M_reg_getb[0+7-:8];
        io_led[8+7-:8] = M_reg_getb[8+7-:8];
        if (io_button[1+0-:1]) begin
          M_state_d = OUTPUT_state;
        end else begin
          if (io_button[0+0-:1]) begin
            M_state_d = INPUTA_state;
          end
        end
      end
      OUTPUT_state: begin
        io_led[0+7-:8] = M_alu_out[0+7-:8];
        io_led[8+7-:8] = M_alu_out[8+7-:8];
        if (io_button[0+0-:1]) begin
          M_state_d = INPUTA_state;
        end else begin
          if (io_button[2+0-:1]) begin
            M_state_d = INPUTB_state;
          end
        end
      end
    endcase
    M_alu_a = M_reg_geta;
    M_alu_b = M_reg_getb;
    M_alu_alufn = io_dip[16+0+5-:6];
    io_led[16+0+7-:8] = io_dip[16+0+7-:8];
    if (autoTest == 1'h1) begin
      M_seg_values = M_autotest_out;
      io_led = M_autotest_leds;
    end
    if (failCase == 1'h1) begin
      M_seg_values = M_fc_out;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
