/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module register_4 (
    input clk,
    input buttonA,
    input buttonB,
    input [15:0] switch,
    output reg [15:0] geta,
    output reg [15:0] getb
  );
  
  
  
  wire [1-1:0] M_button_condA_out;
  button_conditioner_14 button_condA (
    .clk(clk),
    .in(buttonA),
    .out(M_button_condA_out)
  );
  
  wire [1-1:0] M_button_condB_out;
  button_conditioner_14 button_condB (
    .clk(clk),
    .in(buttonB),
    .out(M_button_condB_out)
  );
  
  wire [1-1:0] M_edge1_out;
  edge_detector_16 edge1 (
    .clk(clk),
    .in(M_button_condA_out),
    .out(M_edge1_out)
  );
  wire [1-1:0] M_edge2_out;
  edge_detector_16 edge2 (
    .clk(clk),
    .in(M_button_condB_out),
    .out(M_edge2_out)
  );
  
  reg [15:0] M_registerA_d, M_registerA_q = 1'h0;
  
  reg [15:0] M_registerB_d, M_registerB_q = 1'h0;
  
  always @* begin
    M_registerA_d = M_registerA_q;
    M_registerB_d = M_registerB_q;
    
    if (M_edge1_out) begin
      M_registerA_d = switch;
    end
    if (M_edge2_out) begin
      M_registerB_d = switch;
    end
    geta = M_registerA_q;
    getb = M_registerB_q;
  end
  
  always @(posedge clk) begin
    M_registerA_q <= M_registerA_d;
  end
  
  
  always @(posedge clk) begin
    M_registerB_q <= M_registerB_d;
  end
  
endmodule
