/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    output reg a,
    output reg b,
    output reg carryin,
    input sum,
    input carryout
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  localparam IDLE_state = 4'd0;
  localparam STATE1_state = 4'd1;
  localparam STATE2_state = 4'd2;
  localparam STATE3_state = 4'd3;
  localparam STATE4_state = 4'd4;
  localparam STATE5_state = 4'd5;
  localparam STATE6_state = 4'd6;
  localparam STATE7_state = 4'd7;
  localparam STATE8_state = 4'd8;
  localparam FAIL_state = 4'd9;
  localparam PASS_state = 4'd10;
  
  reg [3:0] M_state_d, M_state_q = IDLE_state;
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [20-1:0] M_seg_values;
  multi_seven_seg_2 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  wire [1-1:0] M_nextState_next_state;
  counting_3 nextState (
    .clk(clk),
    .rst(rst),
    .next_state(M_nextState_next_state)
  );
  
  always @* begin
    M_state_d = M_state_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = {3'h0, io_button};
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_seg_values = 20'h00000;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    io_led = 24'h000000;
    a = io_dip[0+0+0-:1];
    b = io_dip[0+1+0-:1];
    carryin = io_dip[0+2+0-:1];
    if (io_dip[0+7+0-:1] == 1'h1) begin
      if ((io_dip[0+0+0-:1] == 1'h0 & io_dip[0+1+0-:1] == 1'h0 & io_dip[0+2+0-:1] == 1'h0) & (sum == 1'h0 & carryout == 1'h0)) begin
        M_seg_values = 20'h72ca5;
      end else begin
        if ((io_dip[0+0+0-:1] == 1'h0 & io_dip[0+1+0-:1] == 1'h0 & io_dip[0+2+0-:1] == 1'h1) & (sum == 1'h1 & carryout == 1'h0)) begin
          M_seg_values = 20'h72ca5;
        end else begin
          if ((io_dip[0+0+0-:1] == 1'h0 & io_dip[0+1+0-:1] == 1'h1 & io_dip[0+2+0-:1] == 1'h0) & (sum == 1'h1 & carryout == 1'h0)) begin
            M_seg_values = 20'h72ca5;
          end else begin
            if ((io_dip[0+0+0-:1] == 1'h0 & io_dip[0+1+0-:1] == 1'h1 & io_dip[0+2+0-:1] == 1'h1) & (sum == 1'h0 & carryout == 1'h1)) begin
              M_seg_values = 20'h72ca5;
            end else begin
              if ((io_dip[0+0+0-:1] == 1'h1 & io_dip[0+1+0-:1] == 1'h0 & io_dip[0+2+0-:1] == 1'h0) & (sum == 1'h1 & carryout == 1'h0)) begin
                M_seg_values = 20'h72ca5;
              end else begin
                if ((io_dip[0+0+0-:1] == 1'h1 & io_dip[0+1+0-:1] == 1'h0 & io_dip[0+2+0-:1] == 1'h1) & (sum == 1'h0 & carryout == 1'h1)) begin
                  M_seg_values = 20'h72ca5;
                end else begin
                  if ((io_dip[0+0+0-:1] == 1'h1 & io_dip[0+1+0-:1] == 1'h1 & io_dip[0+2+0-:1] == 1'h0) & (sum == 1'h0 & carryout == 1'h1)) begin
                    M_seg_values = 20'h72ca5;
                  end else begin
                    if ((io_dip[0+0+0-:1] == 1'h1 & io_dip[0+1+0-:1] == 1'h1 & io_dip[0+2+0-:1] == 1'h1) & (sum == 1'h1 & carryout == 1'h1)) begin
                      M_seg_values = 20'h72ca5;
                    end else begin
                      M_seg_values = 20'h52d8d;
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    
    case (M_state_q)
      IDLE_state: begin
        if (io_button[1+0-:1]) begin
          M_state_d = STATE1_state;
        end
      end
      STATE1_state: begin
        a = 1'h0;
        b = 1'h0;
        carryin = 1'h0;
        io_led[16+7+0-:1] = 1'h1;
        M_seg_values = 20'h00000;
        if (sum == 1'h0 && carryout == 1'h0 && M_nextState_next_state == 1'h1) begin
          M_state_d = STATE2_state;
        end else begin
          if (sum != 1'h0 || carryout != 1'h0 && M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE2_state: begin
        a = 1'h0;
        b = 1'h0;
        carryin = 1'h1;
        io_led[16+6+0-:1] = 1'h1;
        M_seg_values = 20'h00001;
        if (sum == 1'h1 & carryout == 1'h0 & M_nextState_next_state == 1'h1) begin
          M_state_d = STATE3_state;
        end else begin
          if ((sum != 1'h1 | carryout != 1'h0) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE3_state: begin
        a = 1'h0;
        b = 1'h1;
        carryin = 1'h0;
        io_led[16+5+0-:1] = 1'h1;
        M_seg_values = 20'h00020;
        if (sum == 1'h1 & carryout == 1'h0 & M_nextState_next_state == 1'h1) begin
          M_state_d = STATE4_state;
        end else begin
          if ((sum != 1'h1 | carryout != 1'h0) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE4_state: begin
        a = 1'h0;
        b = 1'h1;
        carryin = 1'h1;
        io_led[16+4+0-:1] = 1'h1;
        M_seg_values = 20'h00021;
        if (sum == 1'h0 & carryout == 1'h1 & M_nextState_next_state == 1'h1) begin
          M_state_d = STATE5_state;
        end else begin
          if ((sum != 1'h0 | carryout != 1'h1) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE5_state: begin
        a = 1'h1;
        b = 1'h0;
        carryin = 1'h0;
        io_led[16+3+0-:1] = 1'h1;
        M_seg_values = 20'h00400;
        if (sum == 1'h1 & carryout == 1'h0 & M_nextState_next_state == 1'h1) begin
          M_state_d = STATE6_state;
        end else begin
          if ((sum != 1'h1 | carryout != 1'h0) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE6_state: begin
        a = 1'h1;
        b = 1'h0;
        carryin = 1'h1;
        io_led[16+2+0-:1] = 1'h1;
        M_seg_values = 20'h00401;
        if (sum == 1'h0 & carryout == 1'h1 & M_nextState_next_state == 1'h1) begin
          M_state_d = STATE7_state;
        end else begin
          if ((sum != 1'h0 | carryout != 1'h1) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE7_state: begin
        a = 1'h1;
        b = 1'h1;
        carryin = 1'h0;
        io_led[16+1+0-:1] = 1'h1;
        M_seg_values = 20'h00420;
        if (sum == 1'h0 & carryout == 1'h1 & M_nextState_next_state == 1'h1) begin
          M_state_d = STATE8_state;
        end else begin
          if ((sum != 1'h0 | carryout != 1'h1) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      STATE8_state: begin
        a = 1'h1;
        b = 1'h1;
        carryin = 1'h1;
        io_led[16+0+0-:1] = 1'h1;
        M_seg_values = 20'h00421;
        if (sum == 1'h1 & carryout == 1'h1 & M_nextState_next_state == 1'h1) begin
          M_state_d = PASS_state;
        end else begin
          if ((sum != 1'h1 | carryout != 1'h1) & M_nextState_next_state == 1'h1) begin
            M_state_d = FAIL_state;
          end
        end
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
      end
      FAIL_state: begin
        M_seg_values = 20'h52d8d;
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
        if (io_button[1+0-:1]) begin
          M_state_d = STATE1_state;
        end
        if (io_button[2+0-:1]) begin
          M_state_d = IDLE_state;
        end
      end
      PASS_state: begin
        M_seg_values = 20'h72ca5;
        if (rst_n == 1'h0) begin
          M_state_d = IDLE_state;
        end
        if (io_button[1+0-:1]) begin
          M_state_d = STATE1_state;
        end
        if (io_button[2+0-:1]) begin
          M_state_d = IDLE_state;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_state_q <= M_state_d;
  end
  
endmodule
